### ISSUE TITLE
LR page need to work without shell page like standalone app

### ISSUE THREAD

**Issue by CodeCode7** [SAP-samples/sap-devtoberfest-2020#101]
Hi Team,
UI Version- 1.97

We successfully created a List report page using CAP + V4LR Page annotations.

However, I want to run the application from index.html without using a shell and have FLP appear in the Home screen. like standalone app .

I modified the index script as shown below.
 data-sap-ui-oninit="module:sap/ui/core/ComponentSupport"

 commented Shell Container .

Remove: sap.ui.getCore().attachInit(function() {
                sap.ushell.Container.createRenderer().placeAt('content');
            });

 <script>
            window['sap-ushell-config'] = {
                defaultRenderer: 'fiori2',
                applications: {
                    'fe-lrop-v4': {
                        title: 'Startos UI',
                        description: 'A Fiori application.',
                        additionalInformation: 'SAPUI5.Component=com.apple.scp.ui.strarosconsumerconfigurationapp',
                        applicationType: 'URL',
                        url: './',
                        navigationMode: 'embedded'
                    }
                }
            };
        </script>

Application loading without FLP look now .

![image](https://user-images.githubusercontent.com/28290714/151290512-e16e8165-a706-4f44-abc0-214688889bc3.png)

However, the first time I create an entry, it works, but the second time I click the create button, the navigation fails. Every time I start a new record, I start with the first one.

If the LR page loads the data, the Create entry will not work again.

![image](https://user-images.githubusercontent.com/28290714/151377606-a31f59ca-e481-41d6-8e7a-58a8a245ba4a.png)

Error :

![image](https://user-images.githubusercontent.com/28290714/151290897-fa4b1e4c-ac04-45d9-9b89-4ffe9f81aaf8.png)

Debug Error :
<img width="1490" alt="Screenshot 2022-01-27 at 8 00 00 PM" src="https://user-images.githubusercontent.com/28290714/151379181-90127db9-71ca-4f0b-94e0-cec986001ddb.png">

**Comment by CodeCode7** [comment]
@IObert could you please help me

**Comment by IObert** [comment]
Sorry, I'm no longer with SAP. But I'll loop in @nicogeburek

**Comment by CodeCode7** [comment]
@IObert
 Thanks for your Help,  @nicogeburek could you please help me

**Comment by nicogeburek** [comment]
Hm looks like something is wrong with the `preferredMode`. Have you tried attaching it as a query parameter to the URL like described (here)[https://help.sap.com/viewer/468a97775123488ab3345a0c48cadd8f/202110.000/en-US/bfaf3ccf3d6d4735990cc793b21f5529.html]. Would be interesting to see what happens.

**Comment by CodeCode7** [comment]
> Hm looks like something is wrong with the `preferredMode`. Have you tried attaching it as a query parameter to the URL like described [here](https://help.sap.com/viewer/468a97775123488ab3345a0c48cadd8f/202110.000/en-US/bfaf3ccf3d6d4735990cc793b21f5529.html)?. Would be interesting to see what happens.




Hi Thanks for reply. I checked this document but sure where i need to add this URL parameter?? Can you please help which file and which section?

**Comment by nicogeburek** [comment]
I just meant adding it to the URL in the address bar of your browser for a test.

Out of curiosity: What is the reason behind having the List Report Object Page run standalone?

**Comment by CodeCode7** [comment]
Basically our client don't have FLP we are deploying apps into different portal and mapping index.html , so client don't want to see shell and setting things.

**Comment by CodeCode7** [comment]
@nicogeburek   I added URL parameter and no luck , can you please help me here

**Comment by CodeCode7** [comment]
@jung-thomas can you please help here

**Comment by jung-thomas** [comment]
@CodeCode7 - I don't think it's supported/designed to run Fiori Elements without at least the uShell.  The generic components have code reliant upon being embedded within the uShell component. But perhaps it would be best to ask this question in a more focused forum.  For example the Fiori Elements section of the Q&A on the SAP Community. https://answers.sap.com/tags/ed5c1ef6-932f-4c19-b2ba-1be375109ff5

**Comment by nicogeburek** [comment]
I did some research on this today and also think it's not a supported feature. One thing I did find though, was that you can run Fiori Launchpad Apps "headerless" (see example [here](https://blogs.sap.com/2014/09/02/fiori-launchpad-sp09-how-to-standalone-headerless-embeded/)). Probably not what you are looking for as your client doesn't have a FLP, but certainly interesting.

**Comment by CodeCode7** [comment]
> I did some research on this today and also think it's not a supported feature. One thing I did find though, was that you can run Fiori Launchpad Apps "headerless" (see example [here](https://blogs.sap.com/2014/09/02/fiori-launchpad-sp09-how-to-standalone-headerless-embeded/)). Probably not what you are looking for as your client doesn't have a FLP, but certainly interesting.


Thanks for your try 👍 ,  our requirement is we are using CAP first time and we want to deploy is in our existing portal which which is combination of multiple apps with developed different technology used.  
As of now we are using freestyle apps and deploying standalone which runs index.html file  .


If FE apps will not support standalone then we can not use future, this is the key point for our client .

Let us know anything can CAP framework can help here .

**Comment by CodeCode7** [comment]
Thank you for your try @nicogeburek . Our requirement is that we are using CAP for the first time and want to deploy it in our existing portal, which is a combination of multiple apps developed using different technologies.
We are currently using freestyle apps and deploying standalone, which runs the index.html file.


If FE apps do not support standalone, we will be unable to use them in the future, which is critical for our client.


Please let us know if the CAP framework can assist you in any way. @jung-thomas @nicogeburek
