### ISSUE TITLE
Workflow Inbox is showing an error instead of a '0'

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/sap-devtoberfest-2020#30]
Please: 

1. Ensure there is a topic label assigned to this issue 
- workflow

2. Specify the exercise number and step number within that exercise. 
- Ex2 towards the end of this Youtube: https://www.youtube.com/watch?v=tG_oUPs67CY

3. Explain as clearly as you can what you're trying to do. 
- Follow the instructions from Ex 1 and Ex 2

Service TASKPROCESSING failed. Contact your system administrator
Show Details:
Error occurred while loading data. Please contact your system administrator.
<!DOCTYPE html><html><head><title>null</title></head><body><h1>Internal Server Error</body></html>

**Comment by qmacro** [comment]
Hi @greg2git it may be permissions, but it's hard to tell from what you report. Which step number in exercise 2 is it? Can you send some more information, for example screenshot of what's happening in the Chrome Developer Tools console? Thanks.

**Comment by greg2git** [comment]
Hi @qmacro 

seems like it was a temporary issue, it's working now but the logs from yesterday are gone. thank you for responding.

rgds,
gm
