### ISSUE TITLE
SAP ABAP Rest Application Programming Model

### ISSUE THREAD

**Issue by RaghuRamNagandla** [SAP-samples/sap-devtoberfest-2020#38]
Hello Thomas, Adam, Rich!!

I have installed Eclipse with ADT Tool but I dont find Create ABAP Cloud Project. So unable to practice the exercises.
Could you please help me with this with steps.
I have used following link:
https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
Kindly help the issue.

Thanks and Regards,
Raghuram

**Comment by jrodriguez-rc** [comment]
Hi @RaghuRamNagandla you need to change perspective.
It is explained in this tutorial (step 2):
https://developers.sap.com/tutorials/abap-create-project.html

**Comment by jung-thomas** [comment]
I'm not sure that changing the perspective is required. As long as you are in a perspect where the Project Explorer is displayed, it seems to work. I just tested it with a different perspective.

Are you ABAP Development Tools patched and up to date? I've seen people with older installations not have this option.  If you look in the Help->About in Eclipse what version of ABAP Development Tools are you running. I'm pretty sure I'm running the latest and I've got 3.12.0.
![image](https://user-images.githubusercontent.com/12159356/91980516-62fb4b00-ecf5-11ea-83ac-e691957ae928.png)

**Comment by jung-thomas** [comment]
@RaghuRamNagandla were you able to solve the issue with the Development Tools?  Or do you need further assistance?

**Comment by RaghuRamNagandla** [comment]
Hi Thomas,

Hope you are doing well.
I am following your sessions on devtoberfest.
Coming to ABAP Restful Programming we need knowledge of SAP ABAP and OOPS
There are many watchers who don't have basic knowledge on SAP ABAP, OOPS
concepts.
It would be much better if there is a course designed on SAP ABAP, OOPS
with Practical Sessions.
So that we can understand the latest topics as well.
Please consider this as my request.

Thanks & Regards,
RaghuRam
9966159091

**Comment by rich-heilman** [comment]
You can start with this video series on ABAP OO basics.  
https://www.youtube.com/watch?v=HAzRVj1NRIM
Cheers,
RIch

**Comment by jung-thomas** [comment]
Actuall that's the old version of the ABAP OO series.  I updated it last year. https://www.youtube.com/playlist?list=PLoc6uc3ML1JT55KwLJVe1QXnsP9emoJG2
