### ISSUE TITLE
What's the timeline for submitting your open source project?

### ISSUE THREAD

**Issue by monalisa0101** [SAP-samples/sap-devtoberfest-2020#43]
When are we suppose to post the open source project(last day for the submission)?
How do we know if the submission is valid?

**Comment by jung-thomas** [comment]
You can post your open source project link as a pull request to the entry.txt file at any time up until the end of the contest period.  There are already a dozen or so entries. Submitting now helps attract others to perhaps contribute to your project.

Valid?  The only technical requirements are the license you use and that you also sign up as an individual on Eventbrite.  If you have other questions about how to submit or about the judging, feel free ask ask here.
