### ISSUE TITLE
Topic CAP Ex-3

### ISSUE THREAD

**Issue by RaghuRamNagandla** [SAP-samples/sap-devtoberfest-2020#44]
Hi Thomas,

I am trying to use SQLlite Tool with the following path
/home/user/projects/Bookshop/bookshop.db

and test the connection, I am getting following error:
You need to install sqlite3@4.1.1 to connect to undefined 

Please help to fix the issue

Thanks and Regards,
Raghuram
9966159091
![CAPSQLite](https://user-images.githubusercontent.com/42440990/92509284-a2f78c00-f227-11ea-9a72-e4809b5afa19.JPG)

![CAPSQLite](https://user-images.githubusercontent.com/42440990/92509215-88251780-f227-11ea-8bca-02b03334ceed.JPG)

**Comment by hemsagarelugu** [comment]
Even for me getting same error

Warm regards
Hemsagar Elugu

**Comment by maxstreifeneder** [comment]
hey folks! thanks for pointing this out. 

could you please execute the following command in /home/user/projects/bookshop (= the project root): 

`npm install -D sqlite3`

Hope that solves the issue. 

Cheers,
Max

**Comment by jhonj98** [comment]
Hi @maxstreifeneder, I tried with the command npm install -D sqlite3, but the result is the same when I'm trying to connect.

![image](https://user-images.githubusercontent.com/10300948/92541047-9a448d00-f20a-11ea-9201-d112237309fa.png)
 
Thanks.

Jhon Jairo.

**Comment by RaghuRamNagandla** [comment]
Hello Max,

Thanks for the quick reply.

I am still facing the same issue.

I am using root path as below:
/home/user/projects/Bookshop/bookshop.db
Bookshop is my project name
bookshop.db is my db connection

Command used to connect is : npm install -D sqlite3

[image: image.png]


----
[image: image.png]

Thanks and Regards,
Raghuram
+91-9966159091

**Comment by maxstreifeneder** [comment]
Hi @RaghuRamNagandla,

could you please show me your bookshop/package.json? 

Cheers,
Max

**Comment by RaghuRamNagandla** [comment]
Hi Max,

This is my json

{
  "name": "Bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^4",
    "express": "^4"
  },
  "devDependencies": {
    "sqlite3": "^4.2.0"
  },
  "scripts": {
    "start": "npx cds run"
  },
  "cds": {
    "requires": {
      "db": {
        "kind": "sqlite",
        "credentials": {
          "database": "bookshop.db"
        }
      }
    }
  }
}
----------------

[image: image.png]

Thank you so much.

Regards,
Raghu Ram Nagandla

**Comment by maxstreifeneder** [comment]
just double-checked, same issue here. Will get back once I have a solution from the development team. 

In the meantime, please use the SQLite CLI to check the database content. (Shown in the same video at [6:44](https://youtu.be/0F2_gqDNcbI?t=404)

Sorry for the inconvenience!

**Comment by RaghuRamNagandla** [comment]
Hey Max,

So kind of you. Please don't use Sorry. I just want to make sure I complete
the exercise correctly and start working on Fiori/UI5 Custom Development on
CAP.
As suggested I will go withCLI method now.

Thank you.
Regards,
Raghuram

**Comment by hemsagarelugu** [comment]
Hi Team,
cant see any db contents when i execute cli commands
![Capture](https://user-images.githubusercontent.com/33831488/92603668-3505a000-f2cd-11ea-8f1c-57050b9a4503.JPG)

Regards
Hemsagar Elugu

**Comment by maxstreifeneder** [comment]
hey @hemsagarelugu, 

the commands start for the SQLite CLI usually start with a dot in the beginning. 

For instance:
`.open bookshop.db`
`.tables`

Cheers,
Max

**Comment by hemsagarelugu** [comment]
Perfect !
![image](https://user-images.githubusercontent.com/33831488/92605226-1902fe00-f2cf-11ea-9601-f5baf18853a3.png)

Regards
Hemsagar

**Comment by maxstreifeneder** [comment]
There will be a fix next week - I'll keep you posted!

**Comment by RaghuRamNagandla** [comment]
Thanks max...

**Comment by maxstreifeneder** [comment]
hey all! 

the issue should be fixed now - a simple stop & start of your Dev Space will bring the fix to your environment. 
Could you please give us feedback if that works for you? 

Cheers,
Max

**Comment by jhonj98** [comment]
Hi @maxstreifeneder, It's working as expected, thank you!!.

![image](https://user-images.githubusercontent.com/10300948/93214456-d441f180-f72a-11ea-934d-91b2a687844c.png)

**Comment by maxstreifeneder** [comment]
brilliant, thanks for the response!
