### ISSUE TITLE
 CAP Ex-5

### ISSUE THREAD

**Issue by jkiran15** [SAP-samples/sap-devtoberfest-2020#46]
Hi,
 While trying to do the exercise -5  i am facing issue with  command :  npm install
giving the below error after run the npm install command. Please check and help.

user: bookshop $ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for sqlite@^4.1.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'bookshop'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-09-10T12_48_57_458Z-debug.log
user: bookshop $ 

![image](https://user-images.githubusercontent.com/38363870/92731341-eeeb2380-f342-11ea-9860-198373db450f.png)

**Comment by maxstreifeneder** [comment]
hi @jkiran15, 

seems like you have installed the wrong package. Could you please try to install the following package?

`npm install sqlite3 -D`

and uinstall the wrong package using: 

`npm uninstall sqlite`

Cheers,
Max

**Comment by jkiran15** [comment]
Thank you Max for reply.
I tried with first with 
npm install sqlite2 -D
i got successful message .
![image](https://user-images.githubusercontent.com/38363870/92745369-4e036500-f350-11ea-8200-7fb25cbcf959.png)

and then tried with uninstall command and got the same error as earlier
npm uninstall sqlite
![image](https://user-images.githubusercontent.com/38363870/92745633-8a36c580-f350-11ea-9ac4-ed829ef7bece.png)

not sure am i the only one getting this error.
thank you for all your help. Max.

**Comment by maxstreifeneder** [comment]
can you please quickly paste your package.json content located the root directory (.../bookshop)?

**Comment by jkiran15** [comment]
please find below:
{
  "_from": "sqlite3@^4.2.0",
  "_id": "sqlite3@4.2.0",
  "_inBundle": false,
  "_integrity": "sha512-roEOz41hxui2Q7uYnWsjMOTry6TcNUNmp8audCx18gF10P2NknwdpF+E+HKvz/F2NvPKGGBF4NGc+ZPQ+AABwg==",
  "_location": "/sqlite3",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "sqlite3@^4.2.0",
    "name": "sqlite3",
    "escapedName": "sqlite3",
    "rawSpec": "^4.2.0",
    "saveSpec": null,
    "fetchSpec": "^4.2.0"
  },
  "_requiredBy": [
    "#DEV:/",
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/sqlite3/-/sqlite3-4.2.0.tgz",
  "_shasum": "49026d665e9fc4f922e56fb9711ba5b4c85c4901",
  "_spec": "sqlite3@^4.2.0",
  "_where": "/home/user/projects/bookshop",
  "author": {
    "name": "MapBox",
    "url": "https://mapbox.com/"
  },
  "binary": {
    "module_name": "node_sqlite3",
    "module_path": "./lib/binding/{node_abi}-{platform}-{arch}",
    "host": "https://mapbox-node-binary.s3.amazonaws.com",
    "remote_path": "./{name}/v{version}/{toolset}/",
    "package_name": "{node_abi}-{platform}-{arch}.tar.gz"
  },
  "bugs": {
    "url": "https://github.com/mapbox/node-sqlite3/issues"
  },
  "bundleDependencies": false,
  "contributors": [
    {
      "name": "Konstantin Käfer",
      "email": "mail@kkaefer.com"
    },
    {
      "name": "Dane Springmeyer",
      "email": "dane@mapbox.com"
    },
    {
      "name": "Will White",
      "email": "will@mapbox.com"
    },
    {
      "name": "Orlando Vazquez",
      "email": "ovazquez@gmail.com"
    },
    {
      "name": "Artem Kustikov",
      "email": "kustikoff@gmail.com"
    },
    {
      "name": "Eric Fredricksen",
      "email": "efredricksen@gmail.com"
    },
    {
      "name": "John Wright",
      "email": "mrjjwright@gmail.com"
    },
    {
      "name": "Ryan Dahl",
      "email": "ry@tinyclouds.org"
    },
    {
      "name": "Tom MacWright",
      "email": "tom@mapbox.com"
    },
    {
      "name": "Carter Thaxton",
      "email": "carter.thaxton@gmail.com"
    },
    {
      "name": "Audrius Kažukauskas",
      "email": "audrius@neutrino.lt"
    },
    {
      "name": "Johannes Schauer",
      "email": "josch@pyneo.org"
    },
    {
      "name": "Nathan Rajlich",
      "email": "nathan@tootallnate.net"
    },
    {
      "name": "AJ ONeal",
      "email": "coolaj86@gmail.com"
    },
    {
      "name": "Mithgol"
    },
    {
      "name": "Ben Noordhuis",
      "email": "ben@strongloop.com"
    }
  ],
  "dependencies": {
    "nan": "^2.12.1",
    "node-pre-gyp": "^0.11.0"
  },
  "deprecated": false,
  "description": "Asynchronous, non-blocking SQLite3 bindings",
  "devDependencies": {
    "@mapbox/cloudfriend": "^1.9.0",
    "aws-sdk": "2.x",
    "eslint": "3.5.0",
    "mocha": "^5.2.0"
  },
  "homepage": "https://github.com/mapbox/node-sqlite3",
  "keywords": [
    "sql",
    "sqlite",
    "sqlite3",
    "database"
  ],
  "license": "BSD-3-Clause",
  "main": "./lib/sqlite3",
  "name": "sqlite3",
  "repository": {
    "type": "git",
    "url": "git://github.com/mapbox/node-sqlite3.git"
  },
  "scripts": {
    "install": "node-pre-gyp install --fallback-to-build",
    "pack": "node-pre-gyp package",
    "pretest": "node test/support/createdb.js",
    "test": "mocha -R spec --timeout 480000"
  },
  "version": "4.2.0"
}

**Comment by jkiran15** [comment]
Thank you . Max!
After changing in package.json file 
   from "sqlite" : "^4.1.1"   to     "sqlite3": "^4.2.0"
I could able to run command : npm install
then it was successful.
![image](https://user-images.githubusercontent.com/38363870/92763048-2963b900-f361-11ea-8708-74950012e2a8.png)
