### ISSUE TITLE
CAP Ex-8 - The debug session type "node-terminal" is not supported

### ISSUE THREAD

**Issue by dsadm** [SAP-samples/sap-devtoberfest-2020#48]
Hi @maxstreifeneder,  

I´m trying to open the debugger (Debug -> Start Debugging) while working on exercise 8 but getting this error message:

**The debug session type "node-terminal" is not supported**

Not sure what to do now! Any hints for me? 

Cheers, 
David

**Comment by mahesh0431** [comment]
@dsadm Same issue for me. Meanwhile, try clicking on the run configuration button on the left side (Play button) and create a configuration and run it, it starts the debugger and is working for me.

Regards,
Mahesh

**Comment by dsadm** [comment]
@mahesh0431 thanks for the hint, that works for me as well!

**Comment by maxstreifeneder** [comment]
thanks @mahesh0431 - that's indeed the preferred alternative! will link this issue below the video
