### ISSUE TITLE
Create Instance failed in SAP HANA Cloud in Trial Account in EU10 - Exercise 10 - CAP (topic-CAP)

### ISSUE THREAD

**Issue by gincyanto** [SAP-samples/sap-devtoberfest-2020#49]
topic-CAP
 EXERCISE NUMBER : 10  STEP NUMBER 1 within that exercise.

I am not able to create instance of SAP HANA Cloud in my trial account in eu10.

It got terminated with below message

 "An error occurred while attempting to create an instance: The request to the service broker timed out: https://service-manager.cfapps.eu10.hana.ondemand.com/v1/osb/9193d17c-64fe-44cb-a46d-a8fb4383fe16/v2/service_instances/75a072ab-c0d6-4592-9085-b7324d39fa73?accepts_incomplete=true"

**Comment by jung-thomas** [comment]
This doesn't sound like a problem with the steps itself but something low level in the infrastructure.  Perhaps just try again a bit later as the problem might have been transitory.  However if this does happen again, let us know and we can try and track down further.

**Comment by gincyanto** [comment]
Hi Thomas,
Now I got a different error. It took some time nearly 5 minutes and gave error " Unable to Load Instances . Connection Lost "

**Comment by jung-thomas** [comment]
I spoke to someone from the HANA Cloud team. They said there were some issues specifically in the EU10 region today that would have impacted HANA Cloud provisioning. That has been fixed now and they suggest that you do try again.

**Comment by gincyanto** [comment]
Hi Thomas,
No luck yet. .Same error as before . " Unable to Load Instances ." 403 - forbidden followed by Connection Lost message

**Comment by jung-thomas** [comment]
Perhaps something has gone wrong with your particular instance because it was created when there were systems problems. Have you tried deleting the HANA instance and recreating from scratch.

**Comment by jung-thomas** [comment]
If you don't mind, could try deleting again and then go to the service instances view as shown here:
![image](https://user-images.githubusercontent.com/12159356/93217608-4587a180-f737-11ea-9d8f-cda0e074e75e.png)
If you could post a screenshot of that, it would be helpful.  We want to make sure that nothing is left over from the failed, original creation process.  

If you do have an service of type SAP HANA Cloud even after deleting it from the SAP HANA Cloud specific tab of the Cockpit, also go ahead and manually delete the service from the service instances view as well.

**Comment by gincyanto** [comment]
Thank you Thomas. My Instance was created  when I logged in today and it is running successfully now.
Thank you for your prompt response.
