### ISSUE TITLE
Devtoberfest dates not clear - need highlighting on home page

### ISSUE THREAD

**Issue by qmacro** [SAP-samples/sap-devtoberfest-2020#50]
(Via Gregor Wolf, thank you) - it's not clear enough when the challenge participation period actually is, and when the judging is. The information is "hidden" in the TOC pages and should really be on the home page. Need to create a new "Important Dates" section.

**Comment by jung-thomas** [comment]
Excellent suggestion @gregorwolf 
I've added via c0d8b4d41b1af94de730115741b6535f482bd5c7

Open to feedback here if this does the t

**Comment by jung-thomas** [comment]
Excellent suggestion @gregorwolf 
I've added via c0d8b4d41b1af94de730115741b6535f482bd5c7

Open to feedback here if this does the trick or if we need to add more.
