### ISSUE TITLE
Ex. 09 - Introducing an app at the UI layer : After clicking on Browse Books title 

### ISSUE THREAD

**Issue by RSLAL** [SAP-samples/sap-devtoberfest-2020#52]
Hello, 
Ex. 09 - Introducing an app at the UI layer

after clicking on tile "Browse Books"  : it does not open next screen , instead open the same screen   

![browsebooks](https://user-images.githubusercontent.com/15990378/93558752-24e46500-f94c-11ea-8685-6d229c89d288.jpg)

**Comment by qmacro** [comment]
Hi there - can you perhaps give us some more information to go on? What messages are in the developer console in your Chrome browser (open up Developer Tools), and which part of Ex.09 had you got to, exactly? Cheers. DJ

**Comment by RSLAL** [comment]
Hello DJ, 
It works now without making any change today .. 
Thanks 
Lal
