### ISSUE TITLE
Exercise 3 deploy to CF not working

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-devtoberfest-2020#55]
Hi @IObert, 

I don't know if I still can report issues but here I go, following the step by step deployment process I got stock in the last step where as you can see in the screenshot, there is not such deployment done, just the info in the console. 

![image](https://user-images.githubusercontent.com/10300948/93946758-bc0c3c80-fcff-11ea-8c04-519ef752a6a2.png)

Please your help, and thanks in advanced.

Jhon Jairo.

**Comment by IObert** [comment]
Hi,

this looks weird because it's not even starting the deployment. Can you double-check you are connected to the CF endpoint?
If the issue still persists, please execute the `cf deploy` command manually from a terminal to see whether the process starts there.

**Comment by jhonj98** [comment]
Hi @IObert, I only retried today the deployment and everything worked as expected.

Thank you.

Jhon Jairo.
