### ISSUE TITLE
Getting 404 for this URL https://github.com/SAP-samples/cloud-apis-virtual-event/

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/sap-devtoberfest-2020#60]
Is the URL above supposed to be live at some point before next week?
thx,
gm

**Comment by jung-thomas** [comment]
If DJ can get 25 likes on his tweet he will release the repo early. Otherwise it will be live next week:

https://twitter.com/qmacro/status/1309047687061409794

**Comment by greg2git** [comment]
aha, i remember the tweet and that i did like it, so maybe if i retweet with this we get more likes.
