### ISSUE TITLE
CAP exercise 8: Debug Console Error "The debug session type "node-terminal" is not supported."

### ISSUE THREAD

**Issue by gsharan007** [SAP-samples/sap-devtoberfest-2020#65]
Hi,
When I trying to debug using "Start Debugging" button on menu bar, I am getting following Error
"The debug session type "node-terminal" is not supported."

I am trying to follow step shown at 7:35 time in exercise 8 of CAP. I would appreciate your help.

Thanks
Gaurav

**Comment by maxstreifeneder** [comment]
Hi @gsharan007, 

please have a look at issue #48 - somebody else already faced the same issue and got helped ;-)

Cheers,
Max
