### ISSUE TITLE
Additional Kyma learning resource

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/sap-devtoberfest-2020#66]
have found this refresher from the class after setting up kyma in the trial account quite relevant even if only to see the progress that has been made between this and last year: 

https://open.sap.com/courses/kyma1

Thank you,
gm

**Comment by jung-thomas** [comment]
Do we want to add a link to the openSAP course to the week's materials?

**Comment by KevinMuessig** [comment]
Sure I'll add it. You can find the link in the readme.md here: https://github.com/SAP-samples/sap-devtoberfest-2020/blob/master/topics/kyma/readme.md

Thanks
