### ISSUE TITLE
Kyma topic - Readme points to wrong video

### ISSUE THREAD

**Issue by sedacrivity** [SAP-samples/sap-devtoberfest-2020#71]
Just a quick remark that on 

https://github.com/SAP-samples/sap-devtoberfest-2020/blob/master/topics/kyma/readme.md

The bottom video image link points to the previous video and not to the correct one with 

SAP Cloud Platform, Kyma runtime - Valentin Vieriu 
--

**Comment by jung-thomas** [comment]
Thank you for point that out. It has been corrected now.
