### ISSUE TITLE
How to set the Fiori elements as an standalone app in order to register in launchpad

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-devtoberfest-2020#72]
Hi @IObert ,

I was asking myself how to create the fiori application you taught us but with the capability of being registered in a Fiori Launchpad site (the new service in cf) in a "easy" way (I already know how to add applications in Fiori launchpad site). I don't know if I am wrong but I have read that I can do it creating the app as standalone approuter, but this option is only visible when creating sapui5 free style application, but not in Fiori elements app.

Could you explain or may be guide me with some links where I can find information?.

Thank you in advanced.

Jhon Jairo.

**Comment by IObert** [comment]
Hi @jhonj98,

I assume you want that your app is automatically exposed in the "content explorer" so you won't have to add it manually in the Launchpad Site Manager, right? As of today, the Fiori Tools (which generated the Fiori Elements project) only support the "standalone approuter" approach but I know that there are working hard to support the "managed by SAP Cloud Platform" approach as well. 

You can follow the instructions in summarized in [this post](https://blogs.sap.com/2020/10/02/serverless-sap-fiori-apps-in-sap-cloud-platform/) to transform your app manually if you need this today.

Does this answer your question?

**Comment by jhonj98** [comment]
Thank you @IObert , The only thing is when I create a Fiori elements application there is not a mta file, but when I create a sapui5 free style app I do see this file, I assume that with the instructions of your post the idea is to create that mta file in order to build and deploy to cf, tell me if I'm wrong. 

Thanks again.

Jhon Jairo.

**Comment by IObert** [comment]
You can run `npm run deploy` to create the mta file (and other resources) :)

**Comment by jhonj98** [comment]
Ok I see, thanks for the information, I'm going to try the steps from your post and see what happens, thank you very much.

Jhon Jairo.

**Comment by IObert** [comment]
I'll close the issue for now. Please reopen if you still face issues
