### ISSUE TITLE
Summarize your question here

### ISSUE THREAD

**Issue by andborsu** [SAP-samples/sap-devtoberfest-2020#84]
Please: 

1. TOPIC:  "SAP Business Application Studio for SAP Fiori Development"

2. EXERCISE NUMBER and also the STEP NUMBER:
       "Prerequisites"    
      "Set Up SAP Business Application Studio for Development"
     https://github.com/SAP-samples/sap-devtoberfest-2020/blob/master/topics/appstudio/prerequisites.md

3. Prerequisite SAP Cloud Platform -> "Set Up SAP Business Application Studio for Development" I read   
   "Please make sure your trial account includes the following entitlements:"

     My trial account has all the listed entitlements EXCEPT for the HTML5 and Destinations.

Although I do have a Connectivity-->Destinations that I was able to "test connect" to ES5.  I just don't know if this is the same Destination as an Entitlement destination.

I appreciate any help you can provide.  So far the look other playing around with SAP BAS seems to be very cool IDE.

thank you

![My account Entitlements - missing Destination and HTML5](https://user-images.githubusercontent.com/73678653/100479505-4b88ef80-30a3-11eb-9537-616cce885854.png)
![Entitlements - HTML5](https://user-images.githubusercontent.com/73678653/100479506-4c218600-30a3-11eb-8fa4-824bfdb3cfc6.png)
![Entitlements - Destination](https://user-images.githubusercontent.com/73678653/100479507-4c218600-30a3-11eb-83d1-bdf396449743.png)

**Comment by IObert** [comment]
Hi @andborsu,

thanks for opening this issue. These entitlements are now always assigned to all subaccounts. This means you don't have to worry about them and you can proceed.

I also updated the GitHub page.
