### ISSUE TITLE
Facing error of sap is not defined.eslint in Business Application Studio

### ISSUE THREAD

**Issue by somyali** [SAP-samples/sap-devtoberfest-2020#85]
I have created Project from Template->SAP Fiori Freestyle->SAP UI5 Application in Business Application Studio. 
I have included oData service as well. I am receiving error as sap is not defined .eslint error.
Can you please explain about the error of this error and how to resolve?

**Comment by IObert** [comment]
Hi,

I know that eslint is something too sensitive and highlight warnings that shouldn't be highlighted. Our development team is working on this. 

You can ignore this for now, thanks for letting us know anyway.
