### ISSUE TITLE
Need to build MTA (mta.yaml) again and again before Run Configuration in Business Application Studio

### ISSUE THREAD

**Issue by somyali** [SAP-samples/sap-devtoberfest-2020#86]
I have created Project from Template->SAP Fiori Freestyle->SAP UI5 Application in Business Application Studio. 
I have included oData service as well and configured Run Configuration.
Whenever I am changing any code in view/manifest/or any other, my latest code is not getting reflected while doing run configuration. I have to execute 'Build MTA' again and again after any change to reflect latest change in Run Configuration.
Please let me know is this the process or I have to do anything to resolve it.

**Comment by IObert** [comment]
Hi,

Do you also use the "deploy" feature are using "build MTA"? If so, that would explain why the changes are not reflected. 
Or maybe your run configuration points to the "dist" folder that contains the built resources.

Please make sure that the run configuration is set up as instructed in the video.

PS: Please use the SAP Community to ask questions that are beyond the scope of the Devtoberfest (in the Devtoberfest we didn't use Fiori Freestyle apps.)

**Comment by somyali** [comment]
Thank you for reply. I am not sure about deploy feature. 
Steps I followed are-
1. Created Project through template
2. Created Table in View
3. Right clicked on mta.yaml and then selected Build MTA
4. Then configured Run Configuration.
