### ISSUE TITLE
SAP Cloud Platform Workflow - Ex.03 - can't get container to run

### ISSUE THREAD

**Issue by xtreemrage** [SAP-samples/sap-devtoberfest-2020#89]
I'm at step [3. Instantiate a container](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/blob/master/exercises/03/readme.md#3-instantiate-a-container) and I'm trying to run the following command: `docker run -p 8443:8443 --name myscc -d scc`. When I check `docker ps` it's not listed as a running container, when I use `docker ps -a` I see that' it's exited.

When I want to see the log of my container with the following command: `docker logs <container_id>` I see the following: 

> Error: Unable to access jarfile plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar

I have used the latest versions when it comes to the downloads:
- sapcc-2.13.1-linux-x64.zip
- sapjvm-8.1.072-linux-x64.rpm

How can I fix this?

**Comment by mk-in** [comment]
@xtreemrage  A little OT. Perhaps you can help. 

Going a step back; how did you manage to complete Ex 2 with the updated booster that is no longer compatible with these exercises.  I'm unable to deploy BPMFLP https://github.com/SAP-samples/sap-devtoberfest-2020/issues/91

Do you have any inputs that might be useful for my case.

**Comment by xtreemrage** [comment]
@mk-in 
I used my trial account and I could deploy it just fine, but with the booster, you don't need BPMFLP. You will get the following:

![image](https://user-images.githubusercontent.com/3008102/120004157-becdd880-bfd6-11eb-87e5-94edb4391de3.png)

That will lead to the workflow "launchpad":
![image](https://user-images.githubusercontent.com/3008102/120004283-dad17a00-bfd6-11eb-94c1-ce52c0f53089.png)

All the workflow definitions/instances/approvals will be in there.

**Comment by mk-in** [comment]
@xtreemrage I skipped Ex.02 for now

At Ex 03 - I face this error too. I used same source files as mentioned by OP.

**Comment by mk-in** [comment]
I fixed this error and encountered this

![image](https://user-images.githubusercontent.com/7939779/121131160-ffd2b200-c84c-11eb-8ce7-25adc4909889.png)

@xtreemrage Just a shot in the dark .. what is your host os ???

**Comment by mk-in** [comment]
**FIXED!**

@xtreemrage - Can you check at your end

Modified the docker file as followed
```
FROM centos:7

RUN yum -y install initscripts which unzip wget net-tools less

COPY sapdownloads /tmp/sapdownloads/
WORKDIR /tmp/sapdownloads/

COPY java /tmp/java/

RUN unzip sapcc*.zip && \
        rpm -i sapjvm*.rpm && \
        rpm -i com.sap.scc*.rpm


ENV JAVA_HOME=/opt/sapjvm_8/


RUN chsh -s /bin/bash sccadmin

EXPOSE 8443
USER sccadmin
WORKDIR /opt/sap/scc/

CMD = ./go.sh
```

**Comment by qmacro** [comment]
Thanks @mk-in ! I'll look into this and see about modifying / updating the sources. Appreciated!

**Comment by qmacro** [comment]
Thanks again folks, I've [updated the README instructions for Exercise 03](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/pull/12), to point directly to the [nzamani/sap-cloud-connector-docker](https://github.com/nzamani/sap-cloud-connector-docker) repository for all the SAP Cloud Connector setup instructions. This is up to date, and I have sent a couple of pull requests to it recently too to help keep it up to date.

Following the instructions in the [nzamani/sap-cloud-connector-docker](https://github.com/nzamani/sap-cloud-connector-docker) repository means that the setup should work fine. 

@mk-in please let me know if there's still a question about the booster (and perhaps open up a new issue if there is, so we can handle it together) - thanks!
