### ISSUE TITLE
SAP Cloud Platform Workflow - Ex.06 - I don't see the "swagger" like documentation

### ISSUE THREAD

**Issue by xtreemrage** [SAP-samples/sap-devtoberfest-2020#90]
I'm at step [2. Find the Workflow API](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/blob/master/exercises/06/readme.md#2-find-the-workflow-api), but I don't see the "swagger" like documentation.

I expected this:
![workflowapisummary](https://user-images.githubusercontent.com/3008102/119358576-0687f380-bca9-11eb-985a-d52abc10a4cc.png)

But got this:
![image](https://user-images.githubusercontent.com/3008102/119358230-b872f000-bca8-11eb-80cf-9d4e62d4f207.png)

The following errors I see in the `console` of chrome.

```js
GET https://api.sap.com/api/1.0/apicockpitcollection/DEFAULT/apis/SAP_CP_Workflow_CF 404

ERROR TypeError: Cannot read property 'parentElement' of null
    at n.swaggerUiOnComplete (apidetails.module.125aa8f3c7ab2e971e1d.chunk.js:1)
    at onComplete (apidetails.module.125aa8f3c7ab2e971e1d.chunk.js:1)
    at t.invokeTask (polyfills.1f45127eac3b2c140373.bundle.js:1)
    at Object.onInvokeTask (vendor.455d9568a7c08f57a654.bundle.js:1)
    at t.invokeTask (polyfills.1f45127eac3b2c140373.bundle.js:1)
    at e.runTask (polyfills.1f45127eac3b2c140373.bundle.js:1)
    at e.invokeTask (polyfills.1f45127eac3b2c140373.bundle.js:1)
    at invoke (polyfills.1f45127eac3b2c140373.bundle.js:1)
    at n.args.<computed> (polyfills.1f45127eac3b2c140373.bundle.js:1)
```

Also when I click any of the "group" I get the above error (`ERROR TypeError:...`).

![image](https://user-images.githubusercontent.com/3008102/119359221-b2c9da00-bca9-11eb-9685-3cb619747111.png)

I have tested this in:
- Chrome - Version 90.0.4430.212 (Official Build) (64-bit)
- FireFox - 88.0.1 (64-bit)

So I can't test it out via the SAP API HUB

**Comment by RohitV85** [comment]
Hi, I have also noticed this issue but intermittently. Try out the API Hub in an incognito window.

**Comment by qmacro** [comment]
Hi there @xtreemrage sorry about the delay. The API Hub has a new design, and there may have been some changes that are now resolved. You'll see the Swagger based API at the original link (https://api.sap.com/api/SAP_CP_Workflow_CF/resource) now:

<img width="1895" alt="screenshot 2021-08-04 at 14 38 39" src="https://user-images.githubusercontent.com/73068/128190809-1f219489-b9a7-4d4f-af90-996380140992.png">
