### ISSUE TITLE
SAP Cloud Platform Workflow - Ex.02 - SAP BTP services changed. Booster mismatch. 

### ISSUE THREAD

**Issue by mk-in** [SAP-samples/sap-devtoberfest-2020#91]
SAP BTP services have changed. The workflow booster results in a mismatch 

The booster now creates 4 services wm_* and 2 subscriptions. Also the role collection bpmservices is missing. 
![image](https://user-images.githubusercontent.com/7939779/119820301-f2453000-bf0e-11eb-8dac-ce59eea47741.png)

After manually fixing the names and adding the roles, role collection and fixing the mta.yml the build task completes successfully. 
![image](https://user-images.githubusercontent.com/7939779/119820964-a8a91500-bf0f-11eb-8a50-4671c8dc80dd.png)
![image](https://user-images.githubusercontent.com/7939779/119821037-bc547b80-bf0f-11eb-98d1-d5d1b0d568b9.png)

However the deploy task results in error while deploying BPMFLP

![image](https://user-images.githubusercontent.com/7939779/119820820-82837500-bf0f-11eb-906a-d30c46633485.png)
![image](https://user-images.githubusercontent.com/7939779/119820524-2fa9bd80-bf0f-11eb-8b59-f1665e3090cb.png)

Appreciate any inputs on possible next steps.

**Comment by RohitV85** [comment]
Hi All,
I am also getting the 'Service operation failed: Controller operation failed: 404 Updating service "default_portal" failed: Not Found: Error creating service "default_portal" from offering "portal" and plan "standard": Service plan standard not found.' when I am trying to deploy the MTA Archive from the BPMServicesFLP project.
Please help me in getting this issue resolved.
Thanks,
Rohit V.

**Comment by xtreemrage** [comment]
@mk-in 
Does this answer your question?
https://github.com/SAP-samples/sap-devtoberfest-2020/issues/89#issuecomment-850484170

**Comment by mk-in** [comment]
> @mk-in
> Does this answer your question?
> [#89 (comment)](https://github.com/SAP-samples/sap-devtoberfest-2020/issues/89#issuecomment-850484170)

Thanks for your inputs. If I understand you correctly, then we need to skip Ex 2 ( build and deploy the zip ) .

**Comment by mk-in** [comment]
> Hi All,
> I am also getting the 'Service operation failed: Controller operation failed: 404 Updating service "default_portal" failed: Not Found: Error creating service "default_portal" from offering "portal" and plan "standard": Service plan standard not found.' when I am trying to deploy the MTA Archive from the BPMServicesFLP project.
> Please help me in getting this issue resolved.
> Thanks,
> Rohit V.

Rohit,
Try to rename the services. The wm_* will be replaced by default_*. Rename the workflow management service as default_portal. Also change the mta.yaml as
`  - name: default_portal
    parameters:
      service-plan: lite
      service: workflowmanagement
    type: org.cloudfoundry.managed-service`

**Comment by xtreemrage** [comment]
> > @mk-in
> > Does this answer your question?
> > [#89 (comment)](https://github.com/SAP-samples/sap-devtoberfest-2020/issues/89#issuecomment-850484170)
> 
> Thanks for your inputs. If I understand you correctly, then we need to skip Ex 2 ( build and deploy the MTA Archive ) .

Yes, to be fair, the deployment worked for me though...

**Comment by RohitV85** [comment]
> > Hi All,
> > I am also getting the 'Service operation failed: Controller operation failed: 404 Updating service "default_portal" failed: Not Found: Error creating service "default_portal" from offering "portal" and plan "standard": Service plan standard not found.' when I am trying to deploy the MTA Archive from the BPMServicesFLP project.
> > Please help me in getting this issue resolved.
> > Thanks,
> > Rohit V.
> 
> Rohit,
> Try to rename the services. The wm_* will be replaced by default_*. Rename the workflow management service as default_portal. Also change the mta.yaml as
> ` - name: default_portal parameters: service-plan: lite service: workflowmanagement type: org.cloudfoundry.managed-service`

Thank you for this suggestion. A part of the MTA failed to download but the overall process was success.

**Comment by mk-in** [comment]
Having completed the entire course; for anyone who's still struggling ... you are safe to skip ex 2. This app is no longer required. Instead you the workflow management service to see workflow definitions and instances. 

Manually create default_* services if you need in any subsequent exercises.
