### ISSUE TITLE
Workflow Exercise 08 - Adding a Service Task to the workflow definition - Issue while running an instance

### ISSUE THREAD

**Issue by RohitV85** [SAP-samples/sap-devtoberfest-2020#92]
Hi All,

I have successfully added the Service Task as explained in the 'Exercise 08 - Adding a Service Task to the workflow definition' to my 'OrderProcess' workflow definition. The build and deploy happened without any errors and then I instantiated it using the Workflow Management --> Monitor Workflows section (not from Postman) with the following payload:
{
    "request": {
        "Id": "HT-1001",
        "Quantity": 5
    }
}

The instance got created but it ended in Erroneous state as the OrderInfo Service task failed with the following error:
GET request to 'https://sapes5.sapdevcenter.comProducts('HT-1001')?sap-client=002' failed.

Please note that the destination to ES5 is working fine for me and I already have a working account for the ES5 server.
Kindly help me in getting this error resolved.

Thanks,
Rohit V.

**Comment by xtreemrage** [comment]
@RohitV85 
Look at the data, some products ID might have changed

**Comment by RohitV85** [comment]
@xtreemrage , Thanks for your response but cud u plz elaborate a bit...

**Comment by xtreemrage** [comment]
@RohitV85 
The ID `HT-1001` needs to exists in the `/Products` so if you check the `/Products` can you find that ID? Maybe you just need to try a different ID.

**Comment by RohitV85** [comment]
@xtreemrage 
Thanks a lot for your response.
The Destination also needed some changes as well as the ID HT-1001 is no longer present. As you pointed correctly.
Appreciate your help... :)
