### ISSUE TITLE
Setting one field non editable in the object page of list report in business application studio using cap annotations

### ISSUE THREAD

**Issue by ShilpaRGowda** [SAP-samples/sap-devtoberfest-2020#93]
I am creating new CAPM project in BAS , and I am using annotations in the project, I am displaying three fields i.e., NAME,MINWIDTH,MAXWIDTH in the list page when user clicks on the particular line items it will navigate to object page where user will be editing all the four fields. I want all the fields to be editable in the object page except for the NAME field.
i.e., NAME- Non ediatble, MINWIDTH-editable,MAXIWDTH-editable.

`using MyService as service from '../../srv/testservice';

annotate MyService.testSet with @(
    UI:{
        LineItem  : [
            {
                $Type : 'UI.DataField',
                Value : ID,
            },
            {
                @readonly : true
                $Type : 'UI.DataField',
                Value : NAME,
            },
            {
                $Type : 'UI.DataField',
                Value : MAXHEIGHT,
            },
        {
            $Type : 'UI.DataField',
            Value : MAXWIDTH,
        },
        ],
        Facets  : [
            {
                $Type: 'UI.ReferenceFacet',
                Label: 'Picture',
                Target: ![@UI.FieldGroup#Main]
            }
        ],
        FieldGroup#Main : {
            $Type : 'UI.FieldGroupType',
            Data:[
                {  
                    @readonly : true,
                    $Type : 'UI.DataField',
                    Value : NAME,
                }
                {
                    $Type : 'UI.DataField',
                    Value : MINWIDTH,
                },
                {
                    $Type : 'UI.DataField',
                    Value : MAXWIDTH,
                },
            ]
        },
        
    }
);
`
I have tried the above code but still it is not working, can anyone please help me on this.

**Comment by jung-thomas** [comment]
Might I suggest that since this is a general question and not directly related to content of one of the tutorials or sessions in Devtoberfest, that it would be better to ask this question in the SAP Community Q&A. But I think what you want here is the Comon.FieldControl annotation:
https://github.com/SAP-samples/cloud-cap-hana-swapi/blob/main/cap/srv/film-fiori.cds#L172
