### ISSUE TITLE
Alingnment in the object page of the list report using cap annotations in business application studio

### ISSUE THREAD

**Issue by ShilpaRGowda** [SAP-samples/sap-devtoberfest-2020#94]
I am displaying five fields in the object page of the list report, is there any possibility that I can align all the fields using annotations in my capm project?

**Comment by jung-thomas** [comment]
Might I suggest that since this is a general question and not directly related to content of one of the tutorials or sessions in Devtoberfest, that it would be better to ask this question in the SAP Community Q&A.
