### ISSUE TITLE
A technical error has occurred. Cannot read property 'Value' of undefined error in object page of list report application in capm project

### ISSUE THREAD

**Issue by ShilpaRGowda** [SAP-samples/sap-devtoberfest-2020#95]
![error2](https://user-images.githubusercontent.com/85287061/120815853-d9bbc200-c56d-11eb-92fb-49ae71bf3c48.PNG)

![error](https://user-images.githubusercontent.com/85287061/120814541-9ca30000-c56c-11eb-8bfd-5b1c4c7a9e20.PNG)

When I am trying to navigate from list page to object page , it is giving the error "A technical error has occurred. Cannot read property 'Value' of undefined error", till afternoon it was working fine locally , but now its not working in business applciation studio.
//my datamodel
`namespace test.db;

entity test{
@title: '{i18n>Pic.ID}'
    key ID: String(32);
    @title: '{i18n>Pic.MINWIDTH}'
    MINWIDTH: Integer;
    @title: '{i18n>Pic.MAXWIDTH}'
    MAXWIDTH: Integer;
    @title: '{i18n>Pic.MINHEIGHT}'
    MINHEIGHT: Integer;
    @title: '{i18n>Pic.MAXHEIGHT}'
    MAXHEIGHT: Integer;
    @title: '{i18n>Pic.CREATEDONDATETIME}'
    CREATEDONDATETIME: Date;
    @title: '{i18n>Pic.LASTUPDATEDDATETIME}'
    LASTUPDATEDDATETIME: Date;
}`
///my annotation code
`using newservice as service from '../../srv/new';

annotate newservice.newset with @(
    UI:{
        LineItem  : [
            {
                
                $Type : 'UI.DataField',
                Value : ID,
            },
            {
                $Type : 'UI.DataField',
                Value : MINWIDTH,
            },
            {
                $Type : 'UI.DataField',
                Value : MINHEIGHT,
            },
            {
                $Type : 'UI.DataField',
                Value : MAXWIDTH,
            },
            {
                $Type : 'UI.DataField',
                Value : MAXHEIGHT,
            },
            
            {
                $Type : 'UI.DataField',
                Value : CREATEDONDATETIME,
            },
            {
                $Type : 'UI.DataField',
                Value : LASTUPDATEDDATETIME,
            },
        ],
        HeaderInfo  : {
            $Type : 'UI.HeaderInfoType',
            TypeName : 'Picture Resolution',
            TypeNamePlural : 'Picture Resoultions',
        },
        Facets  : [{
            $Type : 'UI.ReferenceFacet',
            Label : '{i18n>Picture Resolution}',
            Target : ![@UI.FieldGroup#Main]
        }
            
        ],
        FieldGroup#Main : {
            $Type : 'UI.FieldGroupType',
            Data: [
                {
                    $Type : 'UI.DataField',
                    Value : ID,
                },
            
                {
                    $Type : 'UI.DataField',
                    Value : MINWIDTH,
                
                },
                
                {
                    $Type : 'UI.DataField',
                    Value : MAXWIDTH,
                },
                {
                    $Type : 'UI.DataField',
                    Value : MINHEIGHT,
                },
                {
                    $Type : 'UI.DataField',
                    Value : MAXHEIGHT,
                }, 
            ]
            
        },
        
    }
);`
//my srv code
`using { test.db.test } from '../db/new';

service newservice {

    entity newset @(
        odata.draft.enabled: true
    ) as projection on test;

}`
//my i18n file

`Pic.ID=ID
Pic.MINHEIGHT=Min Height
Pic.MAXHEIGHT=Max Height
Pic.MINWIDTH=Min Width
Pic.MAXWIDTH=Max Width
Pic.CREATEDONDATETIME=Created Date
Pic.LASTUPDATEDDATETIME=Updated Date`

//my test data
ID,MINWIDTH,MAXWIDTH,MINHEIGHT,MAXHEIGHT,CREATEDONDATETIME,LASTUPDATEDDATETIME
2371e2dc-3983-11eb-a78a-f48c50351e47,100,200,300,400,22-01-2021,22-02-2021

Can anyone please let me know why that error is coming?

**Comment by jung-thomas** [comment]
I suggest that you ask this question in the SAP Community Q&A
