### ISSUE TITLE
Error 502 Odata service in fiori elements execution in BAS 

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-devtoberfest-2020#97]
Hi @IObert ,

I followed the tutorial from the link below, but in last days the application returns error 502 when executing the application from BAS, the problem doesn't reproduce when deployed to BTP and executed from there. I hadn't done any change to the app before the error.

![image](https://user-images.githubusercontent.com/10300948/122844636-b318bd80-d2c7-11eb-8e34-4a61cfcb1611.png)

https://github.com/SAP-samples/sap-devtoberfest-2020/blob/master/topics/appstudio/exercises/02.md  

Have you experienced something similar last days, it's a known issue?

Thank you in advanced.

Jhon Jairo.

**Comment by IObert** [comment]
Hi,

thanks for letting us know. I just went through the first few steps until step 5 of [this tutorial](https://developers.sap.com/tutorials/fiori-tools-generate-project.html) and it worked all-fine (I see the data from the ES5 system when running the app).

Is this working to you as well? If so, can you please share which step exactly fails for you?

**Comment by jhonj98** [comment]
Hi Marious, actually, the step where this fails is when I'm running the app from Business Application Studio, when I do it from the HTML5 applications in Cloud foundry runs well.

This is my destination configuration

![image](https://user-images.githubusercontent.com/10300948/122930361-8bf6d600-d331-11eb-966b-b108ed31b15e.png)

Jhon Jairo.

**Comment by IObert** [comment]
Mhhh, that's strage as it works for me :)
Can you confirm that it worked for you before?

**Comment by jhonj98** [comment]
yes, it's very strange because it worked before, this application suddendly stop working running from BAS, I thought it was something in the manifest.json or any other configuration that was affected indirectly by any recent BAS update, that's why I created a new app pointing to the same odata service, but the error persisted.

Jhon Jairo.

**Comment by IObert** [comment]
That is really strange. I just checked and my destination looks same as yours.

**Comment by jhonj98** [comment]
Can you confirm if the odata service name used is ZSEPMRA_PROD_MAN.

**Comment by IObert** [comment]
Yes, it works.
Please note that this service is not available anymore, but `ZSEPMRA_PROD_MAN (1) - OData V2` is (and that one works)

**Comment by jhonj98** [comment]
Precisely, I was talking about ZSEPMRA_PROD_MAN (1). the last thing I want to try is to delete the space and recreate it.

**Comment by IObert** [comment]
Can you just create a new one and try it there (without removing the old one)?

**Comment by jhonj98** [comment]
I can't create a new one without deleting the old one, I already have 2 spaces created, can I install fiori tools in the Workflow space being that a Basic space?

![image](https://user-images.githubusercontent.com/10300948/123288100-e11f1d00-d4d4-11eb-845d-3defdd1503cd.png)

**Comment by IObert** [comment]
I don't think so

**Comment by jhonj98** [comment]
Hi Marious, Definitely I had to delete the SAP Fiori space and create it again, I made a backup of my projects and uploaded it again in the new space, without creating again the apps, and everything works as expected for those apps and for the new ones, no I can  run the applications directly in BAS. 

Regards.

**Comment by IObert** [comment]
Awesome!
I'll close the issue then.
