### ISSUE TITLE
Issue when Creating New Environment in Workflow API for Cloud Foundry

### ISSUE THREAD

**Issue by Nilesh-Crave** [SAP-samples/sap-devtoberfest-2020#99]
[Issue for Workflow API for Cloud Foundry.docx](https://github.com/SAP-samples/sap-devtoberfest-2020/files/7492091/Issue.for.Workflow.API.for.Cloud.Foundry.docx)

Reference url for reproduce the issue:
https://api.sap.com/api/SAP_CP_Workflow_CF/resource

Please find the attachment for issue details.

**Comment by qmacro** [comment]
Hi Nilesh - this is not an issue with the tutorial itself, it's a UI issue (which I suspect may be temporary) on the SAP API Business Hub. From a practical perspective, though - please check if this is still happening, and if not, great. If so, you will need to raise an issue for that, or at least ask in the SAP Community Q&A specifically for the API Business Hub - you can get that here https://community.sap.com/search/?ct=qa&mt=86cfb43d-204e-485e-a52d-41d9e73a5cd8&q=api%20business%20hub&qt=all. Thanks!
